# theme: jekyll-theme-minimal
theme: minima
title: linuxstudysessions
description: just some linux study notes

# remote_theme: pages-themes/hacker@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one